main: ./TicTacToe2/main.c ./TicTacToe2/menus.c ./TicTacToe2/utilities.c include.h min-value.c max-value.c minimax.c terminal.c
	gcc ./TicTacToe2/main.c ./TicTacToe2/menus.c ./TicTacToe2/utilities.c min-value.c max-value.c minimax.c terminal.c -o main
	./main	
